const locations = [
{id:1,name:"Ajanta Caves",region:"Maharashtra",tradition:"Buddhist mural painting",period:"2nd century BCE – 6th century CE",description:"The Ajanta caves preserve major examples of ancient Buddhist mural painting. Their interiors contain narrative scenes, figures and decorative designs associated with Buddhist storytelling.",features:"Narrative murals, expressive figures, ornament and Buddhist themes.",works:"Bodhisattva Padmapani and Jataka narratives.",image:"https://upload.wikimedia.org/wikipedia/commons/c/c5/Ajanta_Padmapani.jpg",credit:"Wikimedia Commons · Ajanta Padmapani",source:"UNESCO World Heritage Centre; Archaeological Survey of India"},
{id:2,name:"Ellora Caves",region:"Maharashtra",tradition:"Rock-cut art & sculpture",period:"6th – 10th century CE",description:"Ellora is a major rock-cut complex containing Buddhist, Hindu and Jain monuments. Its sculptures and architecture show the coexistence of several religious artistic traditions.",features:"Monolithic architecture, sculptural reliefs and multi-religious heritage.",works:"Kailasa Temple (Cave 16) and its sculptural programme.",image:"https://upload.wikimedia.org/wikipedia/commons/2/2d/Kailasa_Temple_at_Ellora_%28Cave_16%29.jpg",credit:"Wikimedia Commons · Kailasa Temple at Ellora",source:"UNESCO World Heritage Centre; Archaeological Survey of India"},
{id:3,name:"Mithila / Madhubani",region:"Bihar",tradition:"Madhubani (Mithila) painting",period:"Living folk tradition",description:"Madhubani painting developed in the Mithila region of Bihar. Traditionally made on walls and floors, it later expanded to paper, cloth and other surfaces.",features:"Bold outlines, dense patterns, geometric borders and nature or mythological imagery.",works:"Rama and Sita, Krishna, Durga, fish, birds and plants.",image:"https://upload.wikimedia.org/wikipedia/commons/d/db/Mithila-Madhubani_Painting.jpg",credit:"Wikimedia Commons · Mithila-Madhubani Painting",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:4,name:"Raghurajpur",region:"Odisha",tradition:"Pattachitra painting",period:"Long-standing temple-linked tradition",description:"Raghurajpur is renowned for Pattachitra, a detailed painting tradition on prepared cloth. The art is closely connected with the Jagannath tradition of Odisha.",features:"Strong outlines, elaborate borders, flat colour fields and mythological storytelling.",works:"Jagannath themes, Krishna Leela, Dashavatara and epic narratives.",image:"https://upload.wikimedia.org/wikipedia/commons/d/de/Pattachitra_Painting_%2816854531288%29.jpg",credit:"Wikimedia Commons · Pattachitra Painting",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:5,name:"Srikalahasti",region:"Andhra Pradesh",tradition:"Kalamkari",period:"Medieval to modern craft tradition",description:"Srikalahasti is associated with the pen-drawn form of Kalamkari, traditionally produced on cotton and used for narrative and temple-related imagery.",features:"Hand-drawn lines, natural dyes and large narrative compositions.",works:"Ramayana, Mahabharata and devotional textile panels.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Kalamkari_painting.jpg/960px-Kalamkari_painting.jpg",credit:"Wikimedia Commons · Kalamkari painting",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:6,name:"Thanjavur",region:"Tamil Nadu",tradition:"Tanjore / Thanjavur painting",period:"Strongly developed under South Indian court and temple patronage",description:"Thanjavur painting is known for devotional subjects and a highly decorative surface, often combining rich colours with gold foil and raised ornament.",features:"Gold foil, raised decoration, vivid colours and devotional imagery.",works:"Images of Hindu deities, saints and temple-associated subjects.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Tanjore_art.jpg/960px-Tanjore_art.jpg",credit:"Wikimedia Commons · Tanjore art",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:7,name:"Warli Region",region:"Maharashtra",tradition:"Warli tribal painting",period:"Living community tradition",description:"Warli painting is associated with Adivasi communities in Maharashtra. Its visual language uses simplified geometric figures to represent everyday life, rituals, agriculture and nature.",features:"White figures on an earthen ground using circles, triangles and lines.",works:"Tarpa dance, farming, weddings, hunting and community life.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Warli_painting.jpg/1280px-Warli_painting.jpg",credit:"Wikimedia Commons · Warli painting",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:8,name:"Mewar / Udaipur",region:"Rajasthan",tradition:"Rajasthani miniature painting",period:"Medieval and early modern court tradition",description:"Rajput painting traditions developed in royal courts and produced illustrated manuscripts, devotional scenes and courtly imagery.",features:"Strong colours, detailed figures, courtly settings and narrative compositions.",works:"Mewar portraits, manuscript paintings and Krishna themes.",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Miniature%20painting%20of%20Maharana%20Pratap%20Singh%20of%20Mewar%20State%2C%20after%20an%20older%20work%2C%20ca.1880.jpg",credit:"Wikimedia Commons · Mewar miniature",source:"Indian art-history references; Wikimedia Commons"},
{id:9,name:"Gond Art Region",region:"Madhya Pradesh",tradition:"Gond painting",period:"Living tribal tradition",description:"Gond art is associated with Gond communities of central India. Contemporary paintings often transform animals, plants and stories into rhythmic compositions filled with dots, lines and internal patterns.",features:"Pattern-filled forms, dots and lines, nature imagery and storytelling.",works:"Trees, animals, birds, village life and natural-world stories.",image:"https://upload.wikimedia.org/wikipedia/commons/b/b2/Gond_Painting.JPG",credit:"Wikimedia Commons · Gond Painting",source:"Ministry of Culture / CCRT; Wikimedia Commons"},
{id:10,name:"Delhi / Mughal Court",region:"Delhi",tradition:"Mughal miniature painting",period:"16th – 19th century",description:"Mughal court ateliers developed a sophisticated miniature painting tradition that combined Persian influences with Indian subjects, techniques and artists.",features:"Fine detail, portraiture, manuscript illustration and court scenes.",works:"Illustrated manuscripts, royal portraits and historical narratives.",image:"https://upload.wikimedia.org/wikipedia/commons/1/1f/Brooklyn_Museum_-_Mughal_Miniature_Painting.jpg",credit:"Wikimedia Commons · Brooklyn Museum Mughal Miniature",source:"National Museum; Ministry of Culture / CCRT; Wikimedia Commons"}
];

// Approximate screen positions over the India outline. These are intentionally simple and responsive.
const pinPositions={1:[54,61],2:[57,62],3:[62,42],4:[68,54],5:[61,66],6:[55,80],7:[47,65],8:[47,49],9:[50,59],10:[57,35]};
const list=document.getElementById('locationList');
const markers=document.getElementById('markers');
const story=document.getElementById('story');
const mapImg=document.getElementById('indiaMap');
const fallback=document.getElementById('mapFallback');

function renderStory(item,scroll=true){
  story.innerHTML=`<div class="story"><div class="story-image"><img src="${item.image}" alt="${item.tradition} at ${item.name}" loading="eager" onerror="this.onerror=null;this.src='https://upload.wikimedia.org/wikipedia/commons/c/c5/Ajanta_Padmapani.jpg';this.nextElementSibling.textContent='Image source: Wikimedia Commons';"><div class="image-credit">${item.credit}</div></div><div class="story-copy"><div class="story-number">LOCATION ${item.id}</div><h2>${item.name}</h2><div class="region">${item.region} · ${item.tradition}</div><p class="lead">${item.description}</p><div class="fact-grid"><div class="fact"><b>Period</b><span>${item.period}</span></div><div class="fact"><b>Key features</b><span>${item.features}</span></div><div class="fact"><b>Representative works</b><span>${item.works}</span></div><div class="fact"><b>Location</b><span>${item.region}, India</span></div></div><div class="story-source">${item.source}</div></div></div>`;
  document.querySelectorAll('.location').forEach(x=>x.classList.toggle('active',Number(x.dataset.id)===item.id));
  document.querySelectorAll('.pin').forEach(x=>x.classList.toggle('active',Number(x.dataset.id)===item.id));
  if(scroll && window.innerWidth<901)story.scrollIntoView({behavior:'smooth',block:'start'});
}
function selectItem(item,scroll=true){renderStory(item,scroll);}

locations.forEach(item=>{
  const b=document.createElement('button');b.className='location';b.dataset.id=item.id;b.innerHTML=`<span class="num">${item.id}</span><span><strong>${item.name}</strong><small>${item.tradition}</small></span>`;b.onclick=()=>selectItem(item,true);list.appendChild(b);
  const p=document.createElement('button');p.className='pin';p.dataset.id=item.id;p.style.left=pinPositions[item.id][0]+'%';p.style.top=pinPositions[item.id][1]+'%';p.innerHTML=`${item.id}<span class="pin-label">${item.name}</span>`;p.title=item.name;p.onclick=()=>selectItem(item,false);markers.appendChild(p);
});

document.getElementById('resetBtn').onclick=()=>{document.querySelectorAll('.location,.pin').forEach(x=>x.classList.remove('active'));story.innerHTML='<div class="story-empty"><div class="story-mark">✦</div><div><div class="eyebrow dark">SELECT A PLACE</div><h2>Click a numbered point to begin.</h2><p>Its artwork, artistic tradition and historical context will appear here.</p></div></div>';window.scrollTo({top:document.getElementById('atlas').offsetTop-20,behavior:'smooth'});};

mapImg.addEventListener('error',()=>{mapImg.hidden=true;fallback.hidden=false});
